name: EpicQuest
main: cc.zoyn.epicquest.EpicQuest
version: 1.0
author: Zoyn
softdepend: [Citizens]
commands:
  epicquest:
    aliases: [eq, quest]
    description: "The EpicQuest's Main Command"
permission:
  eq.help:
    default: op